spring:
  application:
    name: config-client
  profiles:
    active: prod
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/